"""create gold_rates table

Revision ID: 1d3b1e6e7665
Revises: 
Create Date: 2026-07-22 01:00:56.932284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3b1e6e7665'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metal_type', sa.String(), nullable=False),
    sa.Column('purity', sa.String(), nullable=False),
    sa.Column('rate_per_gram', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gold_rate_lookup', 'gold_rates', ['metal_type', 'purity', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_gold_rates_id'), 'gold_rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gold_rates_id'), table_name='gold_rates')
    op.drop_index('ix_gold_rate_lookup', table_name='gold_rates')
    op.drop_table('gold_rates')
    # ### end Alembic commands ###
